[tool.poetry]
name = "flow-field-dataset"
version = "0.1.0"
description = ""
authors = ["Ole Petersen <peteole2707@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.3.0"
h5py = "^3.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
